name: web

on:
  push:
    paths:
      - 'web/**'
      - '.github/**'
  pull_request:
    paths:
      - 'web/**'
      - '.github/**'

jobs:
  site:
    name: "publish docs"
    container: anoff/hugo-asciidoctor
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: |
        cd web
        hugo --gc --minify -d _site --baseURL //docs.devradar.io
        touch _site/.nojekyll
        echo "docs.devradar.io" > _site/CNAME
      name: build hugo page
    - name: publish to gh-pages
      uses: JamesIves/github-pages-deploy-action@master
      env:
        ACCESS_TOKEN: ${{ secrets.ANOFF_GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: web/_site
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
