name: devradar.io - PR

on:
  pull_request:
    paths:
      - 'app/**'
      - '.github/**'

jobs:
  test-lint-eslint:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v1
      with:
        node-version: 12
    - run: npm ci
      working-directory: app
    - run: npm run lint
      name: eslint/standard
      working-directory: app

  test-lint-tsc:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v1
      with:
        node-version: 12
    - run: npm ci
      working-directory: app
    - run: npm run build
      name: tsc build
      working-directory: app

  test-e2e-volatile:
    runs-on: ubuntu-18.04
    env:
      VUE_APP_BACKEND_TYPE: 'testVolatile'
      CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_KEY }}
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v1
      with:
        node-version: 12
    - run: npm ci
      working-directory: app
    - run: |
        npm run build
        npm run test:e2e:run
      name: cypress tests w/ local storage
      working-directory: app

  test-e2e-firebase:
    runs-on: ubuntu-18.04
    env:
      VUE_APP_BACKEND_TYPE: 'firebase'
      VUE_APP_BACKEND_PROJECT: ${{ secrets.FIREBASE_E2E_PROJECT }}
      VUE_APP_BACKEND_KEY: ${{ secrets.FIREBASE_E2E_CLIENTKEY }}
      CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_KEY }}
      FIREBASE_SERVICEACCOUNT: ${{ secrets.FIREBASE_E2E_ACCOUNTKEY }}
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v1
      with:
        node-version: 12
    - run: npm ci
      working-directory: app
    - run: |
        npm i -g firebase-tools
        firebase deploy --only firestore:rules --token ${{ secrets.FIREBASE_E2E_TOKEN }} --project ${{ secrets.FIREBASE_E2E_PROJECT }}
      working-directory: app
      name: deploy firestore rules
    - run: npm run build
      working-directory: app
    - run: |
        npm run test:e2e:run
        # npm run test:e2e:ci:firebase:record # cypress key provided via CYPRESS_RECORD_KEY env variable
      name: cypress tests w/ firebase backend
      working-directory: app
